[package]
name = "PAC-man"
version = "1.0.0"
authors = ["WanzenBug <moritz@wanzenbug.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1"
serde = { version = "1.0", features = ["derive"] }
